my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from shop_app.views import ShopIndexViev

urlpatterns = [
    path('', ShopIndexViev.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('shop/', include('shop_app.urls'))
]

my_site/shop_app/urls.py
from django.urls import path
from .views import (ShopIndexViev,
                    ProductListView,
                    ProductDetailView,
                    OrdersListView,
                    OrderCreateView,
                    OrderDetailView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    OrderDeleteView,
                    OrderUpdateView,
                    
                    )


app_name = 'shop_app'

urlpatterns = [
    
    path('', ShopIndexViev.as_view(), name='index'),
    path('products/', ProductListView.as_view(), name='products_list'),
    path('orders/', OrdersListView.as_view(), name='orders_list'),
    path('orders/create/', OrderCreateView.as_view(), name='create_order'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/archive/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('orders/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),




]

my_site/shop_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    class Meta:
        pass
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    archived = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f"Product(name={self.name!r})"


class Order(models.Model):
    class Meta:
        pass
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(blank=True, max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

    def __str__(self) -> str:
        return f"Order(pk={self.pk})"

my_site/shop_app/forms.py
from django.contrib.auth.models import Group
from django.forms import ModelForm


# class GroupForm(ModelForm):

my_site/shop_app/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import Group

from shop_app.models import Product, Order
from .shop_app_forms import OrderForm
from django.views import View

class ShopIndexViev(View):

    def get( self, request: HttpRequest) -> HttpResponse:
        context = {
            'groups': Group.objects.all(),
        }
        return render(request, 'shop_app/shop-index.html', context=context)
    


# def shop_groups(request: HttpRequest):
#     context = {
        
#     }
#     return render(request, 'shop_app/shop-index.html', context=context)


class ProductListView(ListView):
    template_name = "shop_app/products_list.html"
    model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class ProductDetailView(DetailView):
    template_name = "shop_app/product_detail.html"
    model = Product
    context_object_name = "product"


class ProductCreateView(CreateView):
    model = Product
    fields = "name", "description", "price", "discount"
    success_url = reverse_lazy("shop_app:products_list")


class ProductUpdateView(UpdateView):
    model = Product
    fields = "name", "description", "price", "discount"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shop_app:product_detail",
            kwargs={"pk": self.object.pk},
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shop_app:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(ListView):
    template_name = "shop_app/orders_list.html"
    model = Order
    context_object_name = "orders"


class OrderCreateView(CreateView):
    template_name = "shop_app/create_order.html"
    model = Order
    fields = "delivery_address", "promocode", "user", "products"
    success_url = reverse_lazy("shop_app:orders_list")


class OrderDetailView(DetailView):
    template_name = "shop_app/order_detail.html"
    model = Order
    context_object_name = "orders"


class OrderUpdateView(UpdateView):
    template_name = "shop_app/update_order.html"
    model = Order
    fields = "delivery_address", "promocode", "user", "products"

    def get_success_url(self):
        return reverse(
            "shop_app:order_detail",
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    template_name = "shop_app/order_confirm_delete.html"
    model = Order
    success_url = reverse_lazy("shop_app:orders_list")

my_site/shop_app/templates/shop_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <style>
        h1{
            text-align: center;
        }
        .container{
            width: 1200px;
            height: auto;
            margin: 0 auto;
        }
        .navbar{
            width: 100%;
        }
    </style>
</head>  
<body>
    <div class="container">
        <div class="navbar">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#">Shop App</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000/shop">Главная</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/shop/products">Продукция</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/shop/orders">Заказы</a>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                    </div>
                </div>
            </nav>
    </div>
    </div>
    <div class="container">
        {% block body %}   
        {% endblock %}
    </div>
    
    



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
<header>
    <div class="container">
        <div>
        Сегодня {% now "j F Y" %}
        </div>
        <div>
        {% now 'H:i' %}
        </div>
    </div>       
</header>
</html>

my_site/shop_app/templates/shop_app/create_order.html
{% extends "shop_app/base.html" %}


{% block title %}
    Create Order
{% endblock %}


{% block body %}
<h1>Create a new order</h1>
<br>
<div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create</button>
    </form>
</div>
<div>
    <a href="{% url 'shop_app:orders_list' %}">Back to order list</a>
</div>

{% endblock %}

my_site/shop_app/templates/shop_app/create_product.html
{% extends "shop_app/base.html" %}


{% block title %}
Create Product
{% endblock %}


{% block body %}
<h1>Create a new product</h1>
<br>
<div>
    <form method="post">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit">Create</button>
    </form>
</div>
<div>
    <a href="{% url 'shop_app:products' %}">Back to product list</a>
</div>

{% endblock %}

my_site/shop_app/templates/shop_app/order_confirm_delete.html
{% extends 'shop_app/base.html' %}


{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}


{% block body %}
    <h1>Are you sure you want to delete {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shop_app:order_detail' pk=object.pk %}">Back to order</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/order_detail.html
{% extends 'shop_app/base.html' %}


{% block title %}
    Order #{{ object.id }} details
{% endblock %}


{% block body %}
    <h1>Order #{{ object.id }}</h1>
<div>
    <p>Order by {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: {{ object.promocode }}</p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
        <h2>Product in order</h2>
        <ul>
            {% for product in object.products.all %}
            <li>{{ product.name }} for ${{ product.price }}</li>
            {% endfor %}
        </ul>
    </div>

    <div>
        <a href="{% url 'shop_app:order_delete' pk=object.pk %}">Delete order</a>
    </div>

    <div>
        <a href="{% url 'shop_app:order_update' pk=object.pk%}">Update order</a>
    </div>

    <div>
        <a href="{% url 'shop_app:orders_list' %}">Back to orders list</a>
    </div>
</div>

{% endblock %}

my_site/shop_app/templates/shop_app/order_list.html
{% extends 'shop_app/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders List</h1>
    {% if object_list %}
        <table border="2">
            <tr>
                <th>Детали заказа</th>
                <th>Имя</th>
                <th>Адрес</th>
                <th>Промокод</th>
                <th>Продукция</th>
                <th>Дата и время</th>
            </tr>
            {% for order in object_list %}

                <tr>
                    <td>
                        <a href="{% url 'shop_app:order_detail' pk=order.id %}">
                            Detail {{ order.id }}
                        </a>
                    </td>
                    <td>{{ order.user }}</td>
                    <td>{{ order.delivery_address }}</td>
                    <td>{{ order.promocode }}</td>
                    <td>
                        <ul>
                            {% for product in order.products.all %}
                                <li>{{ product.name }} for {{ product.price }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ order.created_at }}</td>
                </tr>

            {% endfor %}
        </table>
    {% else %}
        <h3>No orders yet!</h3>
    {% endif %}
<div>
    <a href="{% url 'shop_app:create_order' %}">Create a new order</a>
</div>

{% endblock %}

my_site/shop_app/templates/shop_app/product_confirm_delete.html
{% extends 'shop_app/base.html' %}


{% block title %}
    Confirm archive {{ object.name }}
{% endblock %}


{% block body %}
    <h1>Are you sure you want to archive {{ object.name }}?</h1>
    <br>
    <div>
        <a href="{% url 'shop_app:product_detail' pk=object.pk %}">Back to product</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archived</button>
        </form>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/product_detail.html
{% extends 'shop_app/base.html' %}

{% block title %}
    Product #{{ product.id }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
    </div>
    <div>
        <a href="{% url 'shop_app:product_update' pk=product.id %}">Update product</a>
    </div>
    <div>
        <a href="{% url 'shop_app:products_list' %}">Back to products list</a>
    </div>
    <div>
        <a href="{% url 'shop_app:product_delete' pk=product.id %}">Archived product</a>
    </div>
{% endblock %}

my_site/shop_app/templates/shop_app/product_form.html
{% extends 'shop_app/base.html' %}


{% block title %}
    Create product
{% endblock %}


{% block body %}
<h1>Create product</h1>
<div>
    <form method="post" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
</div>
<div>
    <a href="{% url 'shop_app:products_list' %}">Back to products list</a>
</div>

{% endblock %}

my_site/shop_app/templates/shop_app/product_update_form.html
{% extends 'shop_app/base.html' %}


{% block title %}
    Create product
{% endblock %}


{% block body %}
<h1>Update form</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
</div>
<div>
    <a href="{% url 'shop_app:product_detail' pk=object.pk %}">Back to a product #{{ object.pk }}</a>
</div>

{% endblock %}

my_site/shop_app/templates/shop_app/products_list.html
{% extends 'shop_app/base.html' %}

{% block title %}
    
{% endblock %}

{% block body %}
    <h1>Products</h1>
    {% if products %}
        <table border="2">
            <tr>
                <th>#</th>
                <th>Название</th>
                <th>Цена</th>
                <th>Скидка (%)</th>
                <th>Описание продукта</th>
            </tr>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>
                        <a href="{% url 'shop_app:product_detail' pk=product.id %}">
                            {{ product.name }}
                        </a>
                    </td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.discount }}</td>
                    <td>{{ product.description }}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h3>No products yet!</h3>
    {% endif %}


<div>
    <a href="{% url 'shop_app:product_create' %}">
        Create a new product
    </a>
</div>

{% endblock %}

my_site/shop_app/templates/shop_app/shop-index.html
{% extends 'shop_app/base.html' %}



{% block title %}
    Запчасти для спецтехники
{% endblock %}

{% block body %}
<h1>Запчасти для спецтехники</h1>
{{ groups }}


{% endblock %}

my_site/shop_app/templates/shop_app/update_order.html
{% extends 'shop_app/base.html' %}


{% block title %}
    Update order
{% endblock %}


{% block body %}
<h1>Update order</h1>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
</div>
<div>
    <a href="{% url 'shop_app:order_detail' pk=object.pk %}">Back to the order #{{ object.pk }}</a>
</div>

{% endblock %}